// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using engie_dashboard.Models;

namespace engie_dashboard.Migrations
{
    [DbContext(typeof(ModelContext))]
    [Migration("20190706144038_Dashengie")]
    partial class Dashengie
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("engie_dashboard.Models.HistoricoSolicitacao", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("HoraModificacao");

                    b.Property<string>("SolicitacaoId");

                    b.Property<string>("UsuarioId");

                    b.HasKey("Id");

                    b.HasIndex("SolicitacaoId");

                    b.ToTable("HistoricoSolicitacao");
                });

            modelBuilder.Entity("engie_dashboard.Models.Solicitacao", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("EncaminhadoId");

                    b.Property<int>("EstadoOperacional");

                    b.Property<DateTime>("HoraSolicitacao");

                    b.Property<string>("OperadorId");

                    b.Property<int>("StatusSolicitacao");

                    b.Property<int>("TipoSolicitacao");

                    b.Property<string>("UG");

                    b.Property<string>("UnidadeMedida");

                    b.Property<string>("Usina");

                    b.Property<string>("Valor");

                    b.Property<string>("VerificadorId");

                    b.HasKey("Id");

                    b.ToTable("Solicitacao");
                });

            modelBuilder.Entity("engie_dashboard.Models.HistoricoSolicitacao", b =>
                {
                    b.HasOne("engie_dashboard.Models.Solicitacao")
                        .WithMany("HistoricosSolicitacao")
                        .HasForeignKey("SolicitacaoId");
                });
#pragma warning restore 612, 618
        }
    }
}
